language: c
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

script:
  - git clone https://github.com/TheFutureShell/QtPluginInjector
  - cd QtPluginInjector
  - export IC=$(git rev-parse --short HEAD)
  - cd ..
  - rm -rf QtPluginInjector
  - mkdir build
  - cd build
  - cmake .. -DQT_PLUGIN_INJECTOR_COMMIT_STR=$IC -DCMAKE_INSTALL_PREFIX=/usr -DGIT_COMMIT_STR=$(git rev-parse --short HEAD)
  - make -j$(nproc)
  - make install DESTDIR=../appdir
  - cd ..
  - mkdir appdir/data
  - cd appdir/data
  - bash scripts/download_xcb_plugins.sh
  - bash scripts/download_bridges.sh
  - cd ..
  - cd ..
  - wget -q http://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - chmod +x linuxdeploy-x86_64.AppImage
  - export VERSION="continuous"
  - ./linuxdeploy-x86_64.AppImage --appdir appdir --output appimage

after_success:
  - wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - bash upload.sh updatedeployqt*.AppImage updatedeployqt*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
